# Generated by Django 5.1 on 2024-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_or_news',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='NE', max_length=2), max_length=140),
        ),
    ]
